services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo_storage:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASS}

  auth-service:
    build: ./auth_service
    container_name: auth-service
    restart: always
    depends_on:
      - mongo
    env_file:
      - .env
    ports:
      - "${AUTH_API_PORT}:${AUTH_API_PORT}"
    environment:
      API_PORT: ${AUTH_API_PORT}
      MONGO_URI: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:27017/${MONGO_DB}?authSource=admin
      JWT_SECRET: ${JWT_SECRET}
    
  videos-service:
    build: ./videos_service
    container_name: videos-service
    restart: always
    depends_on:
      - mongo
      - rabbitmq
    env_file:
      - .env
    ports:
      - "${VIDEOS_API_PORT}:${VIDEOS_API_PORT}"
    environment:
      API_PORT: ${VIDEOS_API_PORT}
      MONGO_URI: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:27017/${MONGO_DB}?authSource=admin
      RABBIT_URI: amqp://${RABBIT_USER}:${RABBIT_PASS}@rabbitmq:5672/
      YOUTUBE_API_KEY: ${YOUTUBE_API_KEY}
      JWT_SECRET: ${JWT_SECRET}

  favorites-service:
      build: ./favorites_service
      container_name: favorites-service
      restart: always
      depends_on:
        - mongo
        - rabbitmq
      env_file:
        - .env
      environment:
        MONGO_URI: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:27017/${MONGO_DB}?authSource=admin
        RABBIT_URI: amqp://${RABBIT_USER}:${RABBIT_PASS}@rabbitmq:5672/
volumes:
  mongo_storage:
